package gemini

import (
	"github.com/ClareAI/astra-voice-service/pkg/logger"
	"go.uber.org/zap"
)

// handleModelText handles text generated by Gemini.
func (h *Handler) handleModelText(connectionID string, text string) {
	logger.Base().Info("Gemini generated text", zap.String("connection_id", connectionID), zap.String("text", text))
	// Add to conversation history if needed
	if h.ConnectionGetter != nil {
		if conn := h.ConnectionGetter(connectionID); conn != nil {
			conn.AddMessage("assistant", text)
		}
	}
}

// handleModelAudio handles audio generated by Gemini (not used if using audio tracks).
func (h *Handler) handleModelAudio(connectionID string, data string) {
	logger.Base().Debug("Gemini generated audio data", zap.String("connection_id", connectionID), zap.Int("length", len(data)))
	// Gemini Multimodal Live usually sends audio via RTP tracks, but inlineData is possible.
}

// handleInterruption handles Gemini being interrupted by user.
func (h *Handler) handleInterruption(connectionID string) {
	logger.Base().Info("Gemini response interrupted", zap.String("connection_id", connectionID))
}

// onModelReady handles when Gemini is ready for interaction.
func (h *Handler) onModelReady(connectionID string) {
	logger.Base().Info("Gemini model ready", zap.String("connection_id", connectionID))
}

